---
name: Style-enforcer
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'src/**'
      - 'test/**'
      - 'docs/**'
      - '.github/workflows/style.yml'
jobs:
  format-check:
    name: Style Enforcement (Julia ${{ matrix.julia-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [min]
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v3
      - name: Install JuliaFormatter
        shell: julia --project=@format --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(; name="JuliaFormatter", version="2"))
      - name: Check formatting
        shell: julia --project=@format --color=yes {0}
        run: |
          using JuliaFormatter
          format("."; verbose=true) || exit(1)
      # Add formatting suggestions to non-draft PRs when "Check formatting" fails
      - uses: reviewdog/action-suggester@v1
        if: ${{ !success() && !cancelled() && github.event_name == 'pull_request' && github.event.pull_request.draft == false }}
        with:
          tool_name: JuliaFormatter
